/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "rcc.h"
#include "gpio.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
rcc_ahb1_clk_enable(RCC_GPIOA);
gpio_pin_mode(GPIOA, gpio_pin5, output_push_pull);
gpio_pin_pull(GPIOA, gpio_pin5, no_pull);

gpio_pin_write(GPIOA, gpio_pin5, gpio_high);
    /* Loop forever */
	while (1)
	{

	}
}
